### ISSUE TITLE
Maybe include this in the official i18next

### ISSUE THREAD

**Issue by spieglio** [i18next/i18next-webtranslate#12]
My idea is the following:

The server already needs to do some stuff to provide the WebTranlate routes. Why not include this webinterface and give the dev the options to server this too.

### Example:
```
i18n.serveWebTranslate(app, {
      i18nextWTOptions: {
        interfacePath: 'locales'
        ...(all the other options)...
      }
  })
```

# UPDATE

Just noticed that it actually is in there. But I had to look into the code of i18next-node to find out how to reach it. Maybe document it somewhere!

**Comment by darthmelak** [comment]
2 years later still 0 mention of the default webtranslate route in the docs....

**Comment by jamuhl** [comment]
missed that one due closing to early...sorry. will reopen this and add that information asap.

**Comment by jamuhl** [comment]
Personally i deprecated i18next-webtranslate as i won't have the time to update it to be compatible with v2 of i18next.

Would be glad to pass ownership over if someone likes to take over...
