### ISSUE TITLE
custom keyseperator and nsseparator not working

### ISSUE THREAD

**Issue by ephemer** [i18next/i18next-webtranslate#15]
Hi, I'm having trouble using a custom keyseparator. I'm serving i18next and WT from node:

  i18n.init({
    supportedLngs: ['en', 'de'],
    keyseparator: ':::',
    nsseparator: ':-:-:',
    ns: { namespaces: ob_namespaces, defaultNs: 'common'},
  ...

  i18nextWTOptions: {
    languages: ['de', 'en'],
    namespaces: ob_namespaces,
    keyseparator: ':::',
    nsseparator: ':-:-:',
  ...

my translation keys show up in the web translate window, but with the default namespace separators (".") also added.

![image](https://f.cloud.github.com/assets/5485935/1859229/0fa5ba9e-779f-11e3-9a0a-44f079bac42f.png)

when i add translations in another language, they're not saved correctly in the json file, and aren't read correctly by i18n.

my translation .json file looks like this (structured as it should be).

{
  "00__.features_container": {
    ".features_stage": {
      ".headline": [
        ".... the translation ...."
      ]
    }
  },
...

But if I save a new translation in WT, I end up with a json file like this:

{
  "00__.features_container..features_stage..headline": [
        ".... the translation ...."
      ]
  ...

Does WT not support custom key separators, or am I doing something wrong?

Thank you!

**Comment by jamuhl** [comment]
Personally i deprecated i18next-webtranslate as i won't have the time to update it to be compatible with v2 of i18next.

Would be glad to pass ownership over if someone likes to take over...
