### ISSUE TITLE
Gruntfile is missing

### ISSUE THREAD

**Issue by asavin** [i18next/i18next-webtranslate#17]
Apparently Gruntfile is missing from the project? When running Grunt getting this:

    $ grunt release
    A valid Gruntfile could not be found. Please see the getting started guide for
    more information on how to configure grunt: http://gruntjs.com/getting-started
    Fatal error: Unable to find Gruntfile.

**Comment by jamuhl** [comment]
Personally i deprecated i18next-webtranslate as i won't have the time to update it to be compatible with v2 of i18next.

Would be glad to pass ownership over if someone likes to take over...
