### ISSUE TITLE
Project incompatible with Express 4.0

### ISSUE THREAD

**Issue by asavin** [i18next/i18next-webtranslate#18]
In `package.json` current config allows version update for Express to use new 4.0. This, however, results in errors when running the app:

$ node server.js
currentLng set to: dev

/Users/alex/github/i18next-webtranslate/server.js:18
app.configure(function() {
    ^
TypeError: Object function (req, res, next) {
    app.handle(req, res, next);
  } has no method 'configure'
    at Object.<anonymous> (/Users/alex/github/i18next-webtranslate/server.js:18:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by mbirnbac** [comment]
Hi, is there any update on this? We use nodejs and express 4. I'm not sure from your comment on this issue if it's recommended or not using the express integration explained in the docs. What's the recommended way of serving localized express templates?

http://i18next.com/node/pages/doc_express.html

Thanks!
Marcelo

**Comment by jamuhl** [comment]
nope...honestly with i18next v2 my plan is to deprecate this project.

**Comment by jamuhl** [comment]
Personally i deprecated i18next-webtranslate as i won't have the time to update it to be compatible with v2 of i18next.

Would be glad to pass ownership over if someone likes to take over...
