### ISSUE TITLE
App translations doesn't work

### ISSUE THREAD

**Issue by asavin** [i18next/i18next-webtranslate#19]
Any idea why translations might not work? Currently getting this:

![i18next_-_webtranslate](https://cloud.githubusercontent.com/assets/487468/2721216/69a8f5b0-c579-11e3-8fbf-45ca12868f34.png)

**Comment by jamuhl** [comment]
Personally i deprecated i18next-webtranslate as i won't have the time to update it to be compatible with v2 of i18next.

Would be glad to pass ownership over if someone likes to take over...
