### ISSUE TITLE
Demo: Comparison selection doesn't work

### ISSUE THREAD

**Issue by 756gzdz5** [i18next/i18next-webtranslate#23]
Hello,

is it possible, that the demo doesn't work? No matther what I choose under "compare to", the display doesn't change.

**Comment by jamuhl** [comment]
could you try: http://i18next.com/pages/demoWT.html

set compare to `dev` and for each value toggle with the compare button.

seems to work...but might be some browser issue or config issue....could you post more details on the configs?

**Comment by 756gzdz5** [comment]
The following files are not available. Could this be the reason?

http://i18next.com/public/sample_locales/de-DE/ns.common.json
http://i18next.com/public/sample_locales/en/ns.common.json
http://i18next.com/public/sample_locales/en-US/ns.common.json

**Comment by jamuhl** [comment]
nope....means it could load:

http://i18next.com/public/sample_locales/de/ns.common.json
http://i18next.com/public/sample_locales/dev/ns.common.json

and the other locales are not yet translated....so one could compare `dev` to `de`.

wondering why it does not work for you?!? do you use chrome browser?

**Comment by 756gzdz5** [comment]
I looked at it once again and found out, that when ich click the compare button corresponding to app.company.name, the comparison value actually displays and stays visible. However, after clicking the compare button off the add key, the comparison value appears and quickly disappears again. The following error is printed to the console: `GET http://i18next.com/public/locales/change.json?= 404 (Not Found)`. The error is thrown in `i18nexttWT.js` in the line `u.send(n.hasContent && n.data || null), r = function(e, i) {`.

**Comment by jamuhl** [comment]
ah yes...that demo runs as static github page...so there is no way to update the resources (that's what the hint on top of the page says...).

in 'correctly' configured environment, where the rest routes for changing, removing and adding keys are defined that won't happen.

**Comment by jamuhl** [comment]
Personally i deprecated i18next-webtranslate as i won't have the time to update it to be compatible with v2 of i18next.

Would be glad to pass ownership over if someone likes to take over...
