### ISSUE TITLE
Quo vadis webtranslate?

### ISSUE THREAD

**Issue by atroo** [i18next/i18next-webtranslate#24]
Hi Guys,

we are using i18next in most of our projects and we are also using webtranslate to provide a UI to let third party people translate our projects and just use the new languages. This works pretty well, except that we would like to have some more convenience and we also fixed some smaller bugs (regarding arrays).

So the question is: What is the current state of the webtranslate project?

We have some ideas, what we want to do with it and would help to refactor and extend it, but it's not our intention to fork it and develop our own solution. So, if you are interested, here is, what we intend to to:

- refactor to use gulp and webpack
- multi-project support
    -> handle all project translations in one ui, select them and store them as configured
    -> every project has its own config
    -> if you still want one ui for each project, you just configure one project per ui
- enhance ui to reflect changes 
- integrate our bug fixes

Would love to hear your opinion and get some feedback.

Thanks in advance!

**Comment by jamuhl** [comment]
that sounds awesome...when i started work on i18next most was done out of the need in the current project i worked for. today, i got hard times to keep up with updates on i18next for client and node.js so updates on webtranslate are not something i could really handle anymore.

so i'm more then happy if you want to revive the project and move it to the next level.

I'm really open to give you write/admin access...i'm all in for this...seeing this part of i18next in good hands will be great.

**Comment by atroo** [comment]
Thanks for your answer, much more than i expected :)

We will fork it and start to work on the fork and we stay in contact. I just wanted to make sure that we don't start on an old code base or that our project goals drift apart. I will inform you on our progress.

Cheers!

**Comment by jamuhl** [comment]
great...thanks a lot....looking forward to it. Every help on i18next is very welcome.

**Comment by jamuhl** [comment]
Personally i deprecated i18next-webtranslate as i won't have the time to update it to be compatible with v2 of i18next.

Would be glad to pass ownership over if someone likes to take over...

**Comment by phal0r** [comment]
Hi @jamuhl ,

do you have any replacement for webtranslate or how do you manage your i18n assets? We started with the refactoring in a fork, but we were pretty busy lately, so there was not much progress.

**Comment by jamuhl** [comment]
@phal0r maintaining this repo was just to much beside all the other repos around i18next. even more on timeline with v2 rewrite which was needed.

But some replacement for the webtranslate ui is planned. But no real plan for release yet.

**Comment by phal0r** [comment]
Ok, so it's a maybe :)

I would suggest the following: I will ask you again, when we have concrete plans to schedule development again and see what your current plans are and if it makes sense to work on this project or not.

**Comment by jamuhl** [comment]
completely agree ;)
