### ISSUE TITLE
i18next-doc link points to 404 page in i18next-webtranslate

### ISSUE THREAD

**Issue by ghachey** [i18next/i18next-webtranslate#25]
I'm not sure I got the WT properly working yet, I don't see the languages or anything in the body. But I do see the top navigation bar and the link to the docs seems broken.

**Comment by jamuhl** [comment]
you mean that page http://i18next.com/pages/demoWT.html

should work in chrome and yes the back link to docs is broken...leads to outdated project page

**Comment by ghachey** [comment]
Well, the one I got working on my own computer from the repo, but I assume it is more or less the same as the online one. Anyway, I moved on to something else. i18next-webtranslate is just not at a level I require for the people that will be using it. I opted to use i18next with gettext backend and deploy Pootle to manage po files for now. Great work on i18next BTW.

**Comment by jamuhl** [comment]
yes....i18next-webtranslate is just an alternative if one does not want to invest in a real translation workflow. -> for smaller projects.

glad you found a toolchain for your usecase.

**Comment by jamuhl** [comment]
Personally i deprecated i18next-webtranslate as i won't have the time to update it to be compatible with v2 of i18next.

Would be glad to pass ownership over if someone likes to take over...
